#!/usr/bin/env bash

set -euo pipefail

if [[ "$#" < 1 ]]; then
  echo "Usage: $0 analysis_dir [setting=value, ...]" >&2
  exit 1
fi

export DadaNanoBC_ANALYSIS_DIR="$1"
shift

for arg in "$@"; do
  export DadaNanoBC_"$arg"
done

Rscript -e "targets::tar_make()"

Rscript -e 'm <- targets::tar_meta(fields = warnings, complete_only = TRUE); for (i in seq_len(nrow(m))) cat(m$name[i], ": ", m$warnings[i], "\n")'
