#!/usr/bin/env bash

set -euo pipefail

if [[ "$#" < 1 || "$#" > 2 ]]; then
  echo "Usage: $0 analysis_dir [n_workers]" >&2
  exit 1
fi


analysis_dir="$1"
cores=1
if [[ "$#" == 2 ]]; then
  cores="$2"
fi

export DadaNanoBC_ANALYSIS_DIR=$analysis_dir
export DadaNanoBC_WORKERS=$cores
Rscript -e "targets::tar_make()"
