#!/usr/bin/env bash

set -euo pipefail

for arg in "$@"; do
  export DadaNanoBC_"$arg"
done

Rscript -e "targets::tar_make()"

Rscript -e 'm <- targets::tar_meta(fields = warnings, complete_only = TRUE); for (i in seq_len(nrow(m))) cat(m$name[i], ": ", m$warnings[i], "\n")'
